### ISSUE TITLE
--filter. instanceId _self

### ISSUE THREAD

**Issue by miccolis** [cutting-room-floor/swarm#5]
It would be pretty trivial to make `--filter. instanceId _self` work. If you look at the code we've got all the pieces right there already; https://github.com/mapbox/swarm/blob/more_self/index.js#L143-160

/cc @ianshward

**Comment by willwhite** [comment]
What if `_self` would just work for any filter and load up any instances that share the same value as you for a given attribute?

**Comment by miccolis** [comment]
Yea this would also be easy to do. I didn't suggest this first as that way you'd actually implement the `_self` filter for `instanceId` is different than other filters we've got, and a bit more like how the `--region` flag works. Because the instance id is something that the aws API knows about and actually supports querying on we'd be able to add it the the API call and only get info about that instance back.a

I'm not yet sure if it's good idea to differentiate between the filtering we do on a query response and arguments we add to the API query. Perhaps we should have `--filter.Foo and --query.Boo`? I'd rather hide this differentiation from the user. However I think it's very possible for you to add a user tag with the same name as a AWS attribute, in which case we'll need a way to differentiate between them (or we could just decide it's unsupported).

That's what I'm thinking about anyhow. Either way we should get it working.

**Comment by miccolis** [comment]
Just did a bit more work in the `more_self` branch and I think I'm going to pause on it for now. Recent changes cover:
- using `_self` with any TAG. This covers thing like entered as tags on the resource, for example "Name", "Swarm", also "Owner"
- using `_self` with instanceId.

Currently swarm merges user entered tags with actual instance attribute like `instanceId` and `privateDnsName`. Leaving aside whether that's good or not, what it means is that the mechanics behind replacing `_self` are going to be different for tags and attributes. I've made the `instanceId` attribute work directly and I'm NOT going to look into generalizing that for now.

So what we can do now is things like:

`metadata --attribute Name --regions _self --filter.InstanceId _self --filter.Class ui-server`

You'll get the instance name if the instance is a "ui-server" and nothing otherwise.

**Comment by miccolis** [comment]
Merged way back see #4
